- name: Update Packages (fedora)
  dnf:
    name: "*"
    state: latest

- name: Update Packages (Debian)
  apt:
    update_cache: yes
    upgrade: yes

- name: Install essential packages
  package:
    name: "{{ packages }}"
    state: latest

- name: Enable passwordless sudo for "{{ username }}"
  lineinfile:
    dst: /etc/sudoers
    regexp: "^%wheel"
    line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
    validate: "usr/sbin/visudo -cf %s"
