---

- name: Add Defender for Endpoint repository and key
  hosts:
  tasks:

    - name: Add Microsoft APT key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  when: ansible_os_family == "Debian"

- name: Add Microsoft apt repository for MDATP
  apt_repository:
    repo: deb [arch=arm64,armhf,amd64] https://packages.microsoft.com/[distro]/[version]/prod[codename] main
    update_cache: yes
    state: present
    filename: microsoft-[prod]
  when: ansible_os_family == "Debian"

- name: Add Microsoft DNF/YUM key
  rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc
  when: ansible_os_family == "RedHat"

- name: Add  Microsoft yum repository for MDATP
  yum_repository:
    name: packages-microsoft-[prod]
    description: Microsoft Defender for Endpoint
    file: microsoft-[prod]
    baseurl: https://packages.microsoft.com/[distro]/[version]/[prod]/ 
    gpgcheck: yes
    enabled: Yes
  when: ansible_os_family == "RedHat"