---
  - name: Install apps onto Ubuntu Servers
    hosts: ubuntu
    tasks:
    - name: install nano
      apt:
        name: nano
        state: latest

    - name: install nmap
      apt:
        name: nmap
        state: latest
    
    - name: install tcpdump
      apt:
        name: tcpdump
        state: latest
        