---
  - name: Update all local packages on Cent-OS
    hosts: centos
    tasks:
      - name: Ansible update cache and upgrade all packages
        dnf:
          name: "*"
          state: latest
          update_cache: yes 